### ISSUE TITLE
CLI unable to register SDKs

### ISSUE THREAD

**Issue by Mvanbruggen** [PLCnext/PLCnext_CLI#2]
The following error occurs when attempting to register sdk:

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
While exploring the SDK '/home/user/CLI_2020_0/SDK20200/' an error occured.
-> CMake discovered an error.
Error
===================================
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

This has been witnessed in Ubuntu 20.04.1  using CLI v2020.0, and v2020.6.1

**Comment by mluhmann** [comment]
Hello, it looks like CMake (included in our toolchain package) can't find your "make". In general make is part of your ubuntu installation. Please make sure make is installed, otherwise run "apt install build-essential". This package includes make and probably other missing software to develop in c++ in ubuntu.

**Comment by mluhmann** [comment]
The issue will be closed, due to inactivity and no further question.
